language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
addons:
  apt:
    packages:
      - xvfb
      - xauth
      - libgtk-3-dev
script:
  - if [ $TRAVIS_OS_NAME = linux ]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - $TESTCMD -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("Alexya")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("Alexya")); using Coverage; Codecov.submit(process_folder())'